/**
 * Shadowdark Ability Seeds — All abilities from the Shadowdark RPG rules.
 * Types: ancestry_feature, class_feature, talent, spell, skill
 *
 * UUID scheme: 30000000-0000-4000-a000-TTNNNNNNNNNN
 *   TT = type:  01=ancestry, 02=class_feature, 03=talent, 04=spell_priest, 05=spell_wizard, 06=skill
 */

interface AbilitySeed {
    id: string;
    name: string;
    slug: string;
    description: string;
    ability_type: string;
    tier: number;
    class_restriction: string[];
    ancestry_restriction: string[];
    level_requirement: number;
    primary_stat: string | null;
    mechanics: Record<string, any>;
    usage: Record<string, any>;
    source: string;
    is_template: boolean;
    metadata: Record<string, any>;
}

// ═══════════════════════════════════════════════════════════════════
// ANCESTRY FEATURES — one per ancestry, gained at character creation
// ═══════════════════════════════════════════════════════════════════

const ANCESTRY_FEATURES: AbilitySeed[] = [
    {
        id: '30000000-0000-4000-a000-010000000001',
        name: 'Stout',
        slug: 'dwarf_stout',
        description: '+2 HP at start. Roll hit points with advantage at every level.',
        ability_type: 'ancestry_feature',
        tier: 1,
        class_restriction: [],
        ancestry_restriction: ['Dwarf'],
        level_requirement: 1,
        primary_stat: 'CON',
        mechanics: { hp_bonus: 2, hp_roll_advantage: true },
        usage: { per: 'passive' },
        source: 'shadowdark',
        is_template: true,
        metadata: { ancestry: 'Dwarf' },
    },
    {
        id: '30000000-0000-4000-a000-010000000002',
        name: 'Farsight',
        slug: 'elf_farsight',
        description: '+1 bonus to ranged weapon attacks or spellcasting checks.',
        ability_type: 'ancestry_feature',
        tier: 1,
        class_restriction: [],
        ancestry_restriction: ['Elf'],
        level_requirement: 1,
        primary_stat: 'DEX',
        mechanics: { bonus: 1, target: ['ranged_attack', 'spellcasting_check'] },
        usage: { per: 'passive' },
        source: 'shadowdark',
        is_template: true,
        metadata: { ancestry: 'Elf' },
    },
    {
        id: '30000000-0000-4000-a000-010000000003',
        name: 'Keen Senses',
        slug: 'goblin_keen_senses',
        description: 'Cannot be caught by surprise.',
        ability_type: 'ancestry_feature',
        tier: 1,
        class_restriction: [],
        ancestry_restriction: ['Goblin'],
        level_requirement: 1,
        primary_stat: 'WIS',
        mechanics: { immune_to: 'surprise', always_acts_first_round: true },
        usage: { per: 'passive' },
        source: 'shadowdark',
        is_template: true,
        metadata: { ancestry: 'Goblin' },
    },
    {
        id: '30000000-0000-4000-a000-010000000004',
        name: 'Stealthy',
        slug: 'halfling_stealthy',
        description: 'Once per day, become invisible for 3 rounds.',
        ability_type: 'ancestry_feature',
        tier: 1,
        class_restriction: [],
        ancestry_restriction: ['Halfling'],
        level_requirement: 1,
        primary_stat: 'DEX',
        mechanics: { effect: 'invisible', duration_rounds: 3 },
        usage: { per: 'day', charges: 1 },
        source: 'shadowdark',
        is_template: true,
        metadata: { ancestry: 'Halfling' },
    },
    {
        id: '30000000-0000-4000-a000-010000000005',
        name: 'Mighty',
        slug: 'halforc_mighty',
        description: '+1 to attack and damage rolls with melee weapons.',
        ability_type: 'ancestry_feature',
        tier: 1,
        class_restriction: [],
        ancestry_restriction: ['HalfOrc'],
        level_requirement: 1,
        primary_stat: 'STR',
        mechanics: { bonus: 1, target: ['melee_attack', 'melee_damage'] },
        usage: { per: 'passive' },
        source: 'shadowdark',
        is_template: true,
        metadata: { ancestry: 'HalfOrc' },
    },
    {
        id: '30000000-0000-4000-a000-010000000006',
        name: 'Ambitious',
        slug: 'human_ambitious',
        description: 'Gain one additional talent roll at 1st level.',
        ability_type: 'ancestry_feature',
        tier: 1,
        class_restriction: [],
        ancestry_restriction: ['Human'],
        level_requirement: 1,
        primary_stat: null,
        mechanics: { extra_talent_rolls: 1 },
        usage: { per: 'character_creation' },
        source: 'shadowdark',
        is_template: true,
        metadata: { ancestry: 'Human' },
    },
];

// ═══════════════════════════════════════════════════════════════════
// CLASS FEATURES — core abilities gained at level 1
// ═══════════════════════════════════════════════════════════════════

const CLASS_FEATURES: AbilitySeed[] = [
    // ── Fighter ─────────────────────────────────────────────────────
    {
        id: '30000000-0000-4000-a000-020000000001',
        name: 'Weapon Mastery',
        slug: 'fighter_weapon_mastery',
        description: 'Proficient with all weapons and armor, including shields.',
        ability_type: 'class_feature',
        tier: 1,
        class_restriction: ['Fighter'],
        ancestry_restriction: [],
        level_requirement: 1,
        primary_stat: 'STR',
        mechanics: { proficiency: ['all_weapons', 'all_armor', 'shields'] },
        usage: { per: 'passive' },
        source: 'shadowdark',
        is_template: true,
        metadata: { class: 'Fighter' },
    },
    {
        id: '30000000-0000-4000-a000-020000000002',
        name: 'Hauler',
        slug: 'fighter_hauler',
        description: 'Add your Constitution modifier (if positive) to your total gear slots.',
        ability_type: 'class_feature',
        tier: 1,
        class_restriction: ['Fighter'],
        ancestry_restriction: [],
        level_requirement: 1,
        primary_stat: 'CON',
        mechanics: { extra_slots: 'CON_mod_if_positive' },
        usage: { per: 'passive' },
        source: 'shadowdark',
        is_template: true,
        metadata: { class: 'Fighter' },
    },
    {
        id: '30000000-0000-4000-a000-020000000003',
        name: 'Grit',
        slug: 'fighter_grit',
        description: 'Advantage on Strength and Constitution checks (not attacks, just checks).',
        ability_type: 'class_feature',
        tier: 1,
        class_restriction: ['Fighter'],
        ancestry_restriction: [],
        level_requirement: 1,
        primary_stat: 'STR',
        mechanics: { advantage_on: ['STR_check', 'CON_check'] },
        usage: { per: 'passive' },
        source: 'shadowdark',
        is_template: true,
        metadata: { class: 'Fighter' },
    },

    // ── Priest ───────────────────────────────────────────────────────
    {
        id: '30000000-0000-4000-a000-020000000010',
        name: 'Turn Undead',
        slug: 'priest_turn_undead',
        description: 'Hold your holy symbol and force undead within Near to make a CHA save vs your spellcasting check or flee for 1d4+1 rounds.',
        ability_type: 'class_feature',
        tier: 1,
        class_restriction: ['Priest'],
        ancestry_restriction: [],
        level_requirement: 1,
        primary_stat: 'WIS',
        mechanics: { range: 'Near', target: 'undead', save: 'CHA', effect: 'flee', duration: '1d4+1 rounds', requires: 'holy_symbol' },
        usage: { per: 'encounter', charges: 1 },
        source: 'shadowdark',
        is_template: true,
        metadata: { class: 'Priest' },
    },
    {
        id: '30000000-0000-4000-a000-020000000011',
        name: 'Divine Spellcasting',
        slug: 'priest_spellcasting',
        description: 'You can cast divine spells. You know two Tier 1 spells. Make spellcasting checks using WIS to maintain focus.',
        ability_type: 'class_feature',
        tier: 1,
        class_restriction: ['Priest'],
        ancestry_restriction: [],
        level_requirement: 1,
        primary_stat: 'WIS',
        mechanics: { spellcasting: true, known_spells_at_start: 2, spell_tier: 1, check_stat: 'WIS', focus_mechanic: true },
        usage: { per: 'passive' },
        source: 'shadowdark',
        is_template: true,
        metadata: { class: 'Priest' },
    },

    // ── Thief ────────────────────────────────────────────────────────
    {
        id: '30000000-0000-4000-a000-020000000020',
        name: 'Backstab',
        slug: 'thief_backstab',
        description: 'When attacking from hiding or when the target is unaware, deal an extra weapon damage die.',
        ability_type: 'class_feature',
        tier: 1,
        class_restriction: ['Thief'],
        ancestry_restriction: [],
        level_requirement: 1,
        primary_stat: 'DEX',
        mechanics: { extra_damage_dice: 1, condition: 'from_hiding_or_target_unaware', stacks_at_levels: [5, 9] },
        usage: { per: 'passive' },
        source: 'shadowdark',
        is_template: true,
        metadata: { class: 'Thief' },
    },
    {
        id: '30000000-0000-4000-a000-020000000021',
        name: 'Thievery',
        slug: 'thief_thievery',
        description: 'You have advantage on DEX checks for: climbing, sneaking, hiding, pick pocketing, lock picking, and finding/disarming traps.',
        ability_type: 'class_feature',
        tier: 1,
        class_restriction: ['Thief'],
        ancestry_restriction: [],
        level_requirement: 1,
        primary_stat: 'DEX',
        mechanics: { advantage_on: ['climb', 'sneak', 'hide', 'pick_pocket', 'pick_lock', 'find_trap', 'disarm_trap'] },
        usage: { per: 'passive' },
        source: 'shadowdark',
        is_template: true,
        metadata: { class: 'Thief' },
    },

    // ── Wizard ───────────────────────────────────────────────────────
    {
        id: '30000000-0000-4000-a000-020000000030',
        name: 'Arcane Spellcasting',
        slug: 'wizard_spellcasting',
        description: 'You can cast arcane spells. You know three Tier 1 spells. Make spellcasting checks using INT.',
        ability_type: 'class_feature',
        tier: 1,
        class_restriction: ['Wizard'],
        ancestry_restriction: [],
        level_requirement: 1,
        primary_stat: 'INT',
        mechanics: { spellcasting: true, known_spells_at_start: 3, spell_tier: 1, check_stat: 'INT', focus_mechanic: true, requires: 'spellbook' },
        usage: { per: 'passive' },
        source: 'shadowdark',
        is_template: true,
        metadata: { class: 'Wizard' },
    },
    {
        id: '30000000-0000-4000-a000-020000000031',
        name: 'Learning Spells',
        slug: 'wizard_learning_spells',
        description: 'You can learn new spells from scrolls by copying them into your spellbook (requires INT check, DC 15). The scroll is consumed.',
        ability_type: 'class_feature',
        tier: 1,
        class_restriction: ['Wizard'],
        ancestry_restriction: [],
        level_requirement: 1,
        primary_stat: 'INT',
        mechanics: { check_stat: 'INT', dc: 15, consumes: 'scroll', success: 'learn_spell' },
        usage: { per: 'passive' },
        source: 'shadowdark',
        is_template: true,
        metadata: { class: 'Wizard' },
    },
];

// ═══════════════════════════════════════════════════════════════════
// TALENTS — gained on level up via talent roll (2d6 on class table)
// ═══════════════════════════════════════════════════════════════════

const TALENTS: AbilitySeed[] = [
    // ── Fighter Talents ─────────────────────────────────────────────
    {
        id: '30000000-0000-4000-a000-030000000001',
        name: '+1 to Melee and Ranged Attacks',
        slug: 'fighter_talent_attack_bonus',
        description: 'Gain +1 to melee and ranged attack rolls.',
        ability_type: 'talent',
        tier: 1,
        class_restriction: ['Fighter'],
        ancestry_restriction: [],
        level_requirement: 2,
        primary_stat: null,
        mechanics: { bonus: 1, target: ['melee_attack', 'ranged_attack'], stacks: true },
        usage: { per: 'passive' },
        source: 'shadowdark',
        is_template: true,
        metadata: { class: 'Fighter', talent_roll: '2-6' },
    },
    {
        id: '30000000-0000-4000-a000-030000000002',
        name: '+2 to Strength, Dexterity, or Constitution',
        slug: 'fighter_talent_stat_boost',
        description: 'Choose STR, DEX, or CON and increase it by +2 (max 18).',
        ability_type: 'talent',
        tier: 1,
        class_restriction: ['Fighter'],
        ancestry_restriction: [],
        level_requirement: 2,
        primary_stat: null,
        mechanics: { stat_boost: 2, choose_from: ['STR', 'DEX', 'CON'], max: 18 },
        usage: { per: 'level_up' },
        source: 'shadowdark',
        is_template: true,
        metadata: { class: 'Fighter', talent_roll: '7-9' },
    },
    {
        id: '30000000-0000-4000-a000-030000000003',
        name: 'Choose a Weapon Mastery',
        slug: 'fighter_talent_weapon_mastery',
        description: 'Choose one weapon type. +1 damage with that weapon. +1 to crit range (critical on 19-20, etc.)',
        ability_type: 'talent',
        tier: 1,
        class_restriction: ['Fighter'],
        ancestry_restriction: [],
        level_requirement: 2,
        primary_stat: null,
        mechanics: { choose_weapon: true, damage_bonus: 1, crit_range_bonus: 1, stacks: true },
        usage: { per: 'passive' },
        source: 'shadowdark',
        is_template: true,
        metadata: { class: 'Fighter', talent_roll: '10-11' },
    },
    {
        id: '30000000-0000-4000-a000-030000000004',
        name: 'Extra Attack',
        slug: 'fighter_talent_extra_attack',
        description: 'You can make a second attack action each round.',
        ability_type: 'talent',
        tier: 2,
        class_restriction: ['Fighter'],
        ancestry_restriction: [],
        level_requirement: 2,
        primary_stat: null,
        mechanics: { extra_attacks: 1 },
        usage: { per: 'passive' },
        source: 'shadowdark',
        is_template: true,
        metadata: { class: 'Fighter', talent_roll: '12' },
    },

    // ── Priest Talents ──────────────────────────────────────────────
    {
        id: '30000000-0000-4000-a000-030000000010',
        name: '+1 to Melee or Ranged Attacks',
        slug: 'priest_talent_attack_bonus',
        description: 'Gain +1 to melee or ranged attack rolls.',
        ability_type: 'talent',
        tier: 1,
        class_restriction: ['Priest'],
        ancestry_restriction: [],
        level_requirement: 2,
        primary_stat: null,
        mechanics: { bonus: 1, target: ['melee_attack', 'ranged_attack'], stacks: true },
        usage: { per: 'passive' },
        source: 'shadowdark',
        is_template: true,
        metadata: { class: 'Priest', talent_roll: '2-6' },
    },
    {
        id: '30000000-0000-4000-a000-030000000011',
        name: '+1 to Priest Spellcasting',
        slug: 'priest_talent_spellcasting_bonus',
        description: 'Gain +1 to spellcasting checks.',
        ability_type: 'talent',
        tier: 1,
        class_restriction: ['Priest'],
        ancestry_restriction: [],
        level_requirement: 2,
        primary_stat: 'WIS',
        mechanics: { bonus: 1, target: ['spellcasting_check'], stacks: true },
        usage: { per: 'passive' },
        source: 'shadowdark',
        is_template: true,
        metadata: { class: 'Priest', talent_roll: '7-9' },
    },
    {
        id: '30000000-0000-4000-a000-030000000012',
        name: '+2 to Strength or Wisdom',
        slug: 'priest_talent_stat_boost',
        description: 'Choose STR or WIS and increase it by +2 (max 18).',
        ability_type: 'talent',
        tier: 1,
        class_restriction: ['Priest'],
        ancestry_restriction: [],
        level_requirement: 2,
        primary_stat: null,
        mechanics: { stat_boost: 2, choose_from: ['STR', 'WIS'], max: 18 },
        usage: { per: 'level_up' },
        source: 'shadowdark',
        is_template: true,
        metadata: { class: 'Priest', talent_roll: '10-11' },
    },
    {
        id: '30000000-0000-4000-a000-030000000013',
        name: 'Learn New Spell',
        slug: 'priest_talent_new_spell',
        description: 'Learn one additional Priest spell of any tier you can cast.',
        ability_type: 'talent',
        tier: 1,
        class_restriction: ['Priest'],
        ancestry_restriction: [],
        level_requirement: 2,
        primary_stat: 'WIS',
        mechanics: { learn_spell: true, spell_type: 'priest', tier: 'any_available' },
        usage: { per: 'level_up' },
        source: 'shadowdark',
        is_template: true,
        metadata: { class: 'Priest', talent_roll: '12' },
    },

    // ── Thief Talents ───────────────────────────────────────────────
    {
        id: '30000000-0000-4000-a000-030000000020',
        name: '+1 to Backstab Damage Die',
        slug: 'thief_talent_backstab_bonus',
        description: 'Add +1 extra weapon damage die to backstabs.',
        ability_type: 'talent',
        tier: 1,
        class_restriction: ['Thief'],
        ancestry_restriction: [],
        level_requirement: 2,
        primary_stat: 'DEX',
        mechanics: { extra_damage_dice: 1, target: 'backstab', stacks: true },
        usage: { per: 'passive' },
        source: 'shadowdark',
        is_template: true,
        metadata: { class: 'Thief', talent_roll: '2-6' },
    },
    {
        id: '30000000-0000-4000-a000-030000000021',
        name: '+2 to Dexterity or Charisma',
        slug: 'thief_talent_stat_boost',
        description: 'Choose DEX or CHA and increase it by +2 (max 18).',
        ability_type: 'talent',
        tier: 1,
        class_restriction: ['Thief'],
        ancestry_restriction: [],
        level_requirement: 2,
        primary_stat: null,
        mechanics: { stat_boost: 2, choose_from: ['DEX', 'CHA'], max: 18 },
        usage: { per: 'level_up' },
        source: 'shadowdark',
        is_template: true,
        metadata: { class: 'Thief', talent_roll: '7-9' },
    },
    {
        id: '30000000-0000-4000-a000-030000000022',
        name: '+1 to Melee and Ranged Attacks',
        slug: 'thief_talent_attack_bonus',
        description: 'Gain +1 to melee and ranged attack rolls.',
        ability_type: 'talent',
        tier: 1,
        class_restriction: ['Thief'],
        ancestry_restriction: [],
        level_requirement: 2,
        primary_stat: null,
        mechanics: { bonus: 1, target: ['melee_attack', 'ranged_attack'], stacks: true },
        usage: { per: 'passive' },
        source: 'shadowdark',
        is_template: true,
        metadata: { class: 'Thief', talent_roll: '10-11' },
    },
    {
        id: '30000000-0000-4000-a000-030000000023',
        name: 'Evasion',
        slug: 'thief_talent_evasion',
        description: 'When you make a DEX save for half damage, take no damage on success.',
        ability_type: 'talent',
        tier: 2,
        class_restriction: ['Thief'],
        ancestry_restriction: [],
        level_requirement: 2,
        primary_stat: 'DEX',
        mechanics: { save_type: 'DEX', on_success: 'no_damage' },
        usage: { per: 'passive' },
        source: 'shadowdark',
        is_template: true,
        metadata: { class: 'Thief', talent_roll: '12' },
    },

    // ── Wizard Talents ──────────────────────────────────────────────
    {
        id: '30000000-0000-4000-a000-030000000030',
        name: '+1 to Wizard Spellcasting',
        slug: 'wizard_talent_spellcasting_bonus',
        description: 'Gain +1 to spellcasting checks.',
        ability_type: 'talent',
        tier: 1,
        class_restriction: ['Wizard'],
        ancestry_restriction: [],
        level_requirement: 2,
        primary_stat: 'INT',
        mechanics: { bonus: 1, target: ['spellcasting_check'], stacks: true },
        usage: { per: 'passive' },
        source: 'shadowdark',
        is_template: true,
        metadata: { class: 'Wizard', talent_roll: '2-6' },
    },
    {
        id: '30000000-0000-4000-a000-030000000031',
        name: '+2 to Intelligence',
        slug: 'wizard_talent_stat_boost',
        description: 'Increase INT by +2 (max 18).',
        ability_type: 'talent',
        tier: 1,
        class_restriction: ['Wizard'],
        ancestry_restriction: [],
        level_requirement: 2,
        primary_stat: null,
        mechanics: { stat_boost: 2, choose_from: ['INT'], max: 18 },
        usage: { per: 'level_up' },
        source: 'shadowdark',
        is_template: true,
        metadata: { class: 'Wizard', talent_roll: '7-9' },
    },
    {
        id: '30000000-0000-4000-a000-030000000032',
        name: 'Learn New Wizard Spell',
        slug: 'wizard_talent_new_spell',
        description: 'Learn one additional Wizard spell of any tier you can cast.',
        ability_type: 'talent',
        tier: 1,
        class_restriction: ['Wizard'],
        ancestry_restriction: [],
        level_requirement: 2,
        primary_stat: 'INT',
        mechanics: { learn_spell: true, spell_type: 'wizard', tier: 'any_available' },
        usage: { per: 'level_up' },
        source: 'shadowdark',
        is_template: true,
        metadata: { class: 'Wizard', talent_roll: '10-11' },
    },
    {
        id: '30000000-0000-4000-a000-030000000033',
        name: 'Spell Recall',
        slug: 'wizard_talent_spell_recall',
        description: 'Once per day, you can re-cast a spell you lost focus on without a new spellcasting check.',
        ability_type: 'talent',
        tier: 2,
        class_restriction: ['Wizard'],
        ancestry_restriction: [],
        level_requirement: 2,
        primary_stat: 'INT',
        mechanics: { recast_lost_spell: true },
        usage: { per: 'day', charges: 1 },
        source: 'shadowdark',
        is_template: true,
        metadata: { class: 'Wizard', talent_roll: '12' },
    },
];

// ═══════════════════════════════════════════════════════════════════
// SPELLS — Priest & Wizard (Tiers 1-3)
// ═══════════════════════════════════════════════════════════════════

const SPELLS: AbilitySeed[] = [
    // ── Priest Tier 1 ───────────────────────────────────────────────
    {
        id: '30000000-0000-4000-a000-040000000001',
        name: 'Cure Wounds',
        slug: 'spell_cure_wounds',
        description: 'Touch a creature and heal it for 1d8 HP.',
        ability_type: 'spell',
        tier: 1,
        class_restriction: ['Priest'],
        ancestry_restriction: [],
        level_requirement: 1,
        primary_stat: 'WIS',
        mechanics: { range: 'Close', healing: '1d8', target: 'single', school: 'Restoration' },
        usage: { per: 'focus', focus_dc: 10 },
        source: 'shadowdark',
        is_template: true,
        metadata: { spell_type: 'priest', tier: 1 },
    },
    {
        id: '30000000-0000-4000-a000-040000000002',
        name: 'Protection from Evil',
        slug: 'spell_protection_evil',
        description: 'Ward yourself or an ally. +1 AC and advantage on saves vs evil creatures for 10 minutes.',
        ability_type: 'spell',
        tier: 1,
        class_restriction: ['Priest'],
        ancestry_restriction: [],
        level_requirement: 1,
        primary_stat: 'WIS',
        mechanics: { range: 'Close', ac_bonus: 1, advantage_vs: 'evil', duration: '10_minutes', school: 'Abjuration' },
        usage: { per: 'focus', focus_dc: 10 },
        source: 'shadowdark',
        is_template: true,
        metadata: { spell_type: 'priest', tier: 1 },
    },
    {
        id: '30000000-0000-4000-a000-040000000003',
        name: 'Light',
        slug: 'spell_light',
        description: 'An object you touch glows like a torch for 1 hour real time.',
        ability_type: 'spell',
        tier: 1,
        class_restriction: ['Priest', 'Wizard'],
        ancestry_restriction: [],
        level_requirement: 1,
        primary_stat: null,
        mechanics: { range: 'Close', light_range: 'Near', duration_seconds: 3600, school: 'Evocation' },
        usage: { per: 'focus', focus_dc: 10 },
        source: 'shadowdark',
        is_template: true,
        metadata: { spell_type: 'both', tier: 1 },
    },
    {
        id: '30000000-0000-4000-a000-040000000004',
        name: 'Holy Weapon',
        slug: 'spell_holy_weapon',
        description: 'A weapon you touch deals +1d6 radiant damage for 5 rounds.',
        ability_type: 'spell',
        tier: 1,
        class_restriction: ['Priest'],
        ancestry_restriction: [],
        level_requirement: 1,
        primary_stat: 'WIS',
        mechanics: { range: 'Close', bonus_damage: '1d6', damage_type: 'radiant', duration_rounds: 5, school: 'Evocation' },
        usage: { per: 'focus', focus_dc: 10 },
        source: 'shadowdark',
        is_template: true,
        metadata: { spell_type: 'priest', tier: 1 },
    },
    {
        id: '30000000-0000-4000-a000-040000000005',
        name: 'Shield of Faith',
        slug: 'spell_shield_of_faith',
        description: 'An ally within Near gains +2 AC for 5 rounds.',
        ability_type: 'spell',
        tier: 1,
        class_restriction: ['Priest'],
        ancestry_restriction: [],
        level_requirement: 1,
        primary_stat: 'WIS',
        mechanics: { range: 'Near', ac_bonus: 2, duration_rounds: 5, school: 'Abjuration' },
        usage: { per: 'focus', focus_dc: 10 },
        source: 'shadowdark',
        is_template: true,
        metadata: { spell_type: 'priest', tier: 1 },
    },

    // ── Priest Tier 2 ───────────────────────────────────────────────
    {
        id: '30000000-0000-4000-a000-040000000010',
        name: 'Smite',
        slug: 'spell_smite',
        description: 'Your next melee attack deals +2d8 radiant damage.',
        ability_type: 'spell',
        tier: 2,
        class_restriction: ['Priest'],
        ancestry_restriction: [],
        level_requirement: 3,
        primary_stat: 'WIS',
        mechanics: { bonus_damage: '2d8', damage_type: 'radiant', target: 'next_melee_attack', school: 'Evocation' },
        usage: { per: 'focus', focus_dc: 12 },
        source: 'shadowdark',
        is_template: true,
        metadata: { spell_type: 'priest', tier: 2 },
    },
    {
        id: '30000000-0000-4000-a000-040000000011',
        name: 'Restore Health',
        slug: 'spell_restore_health',
        description: 'Heal all creatures within Near for 2d6 HP.',
        ability_type: 'spell',
        tier: 2,
        class_restriction: ['Priest'],
        ancestry_restriction: [],
        level_requirement: 3,
        primary_stat: 'WIS',
        mechanics: { range: 'Near', healing: '2d6', target: 'area_allies', school: 'Restoration' },
        usage: { per: 'focus', focus_dc: 12 },
        source: 'shadowdark',
        is_template: true,
        metadata: { spell_type: 'priest', tier: 2 },
    },

    // ── Wizard Tier 1 ───────────────────────────────────────────────
    {
        id: '30000000-0000-4000-a000-050000000001',
        name: 'Magic Missile',
        slug: 'spell_magic_missile',
        description: 'Launch 3 magic darts that auto-hit. Each deals 1d4+1 force damage.',
        ability_type: 'spell',
        tier: 1,
        class_restriction: ['Wizard'],
        ancestry_restriction: [],
        level_requirement: 1,
        primary_stat: 'INT',
        mechanics: { range: 'Far', damage: '1d4+1', projectiles: 3, auto_hit: true, damage_type: 'force', school: 'Evocation' },
        usage: { per: 'focus', focus_dc: 11 },
        source: 'shadowdark',
        is_template: true,
        metadata: { spell_type: 'wizard', tier: 1 },
    },
    {
        id: '30000000-0000-4000-a000-050000000002',
        name: 'Sleep',
        slug: 'spell_sleep',
        description: 'Put 4d6 HP of creatures to sleep within Near range, starting from the lowest HP creatures.',
        ability_type: 'spell',
        tier: 1,
        class_restriction: ['Wizard'],
        ancestry_restriction: [],
        level_requirement: 1,
        primary_stat: 'INT',
        mechanics: { range: 'Near', hp_pool: '4d6', effect: 'sleep', target: 'area_lowest_hp_first', school: 'Enchantment' },
        usage: { per: 'focus', focus_dc: 11 },
        source: 'shadowdark',
        is_template: true,
        metadata: { spell_type: 'wizard', tier: 1 },
    },
    {
        id: '30000000-0000-4000-a000-050000000003',
        name: 'Burning Hands',
        slug: 'spell_burning_hands',
        description: 'Cone of fire, Close range. All creatures take 2d6 fire damage (DEX save for half).',
        ability_type: 'spell',
        tier: 1,
        class_restriction: ['Wizard'],
        ancestry_restriction: [],
        level_requirement: 1,
        primary_stat: 'INT',
        mechanics: { range: 'Close', damage: '2d6', damage_type: 'fire', save: 'DEX', shape: 'cone', school: 'Evocation' },
        usage: { per: 'focus', focus_dc: 11 },
        source: 'shadowdark',
        is_template: true,
        metadata: { spell_type: 'wizard', tier: 1 },
    },
    {
        id: '30000000-0000-4000-a000-050000000004',
        name: 'Shield',
        slug: 'spell_shield',
        description: 'Reaction: +5 AC until your next turn.',
        ability_type: 'spell',
        tier: 1,
        class_restriction: ['Wizard'],
        ancestry_restriction: [],
        level_requirement: 1,
        primary_stat: 'INT',
        mechanics: { ac_bonus: 5, trigger: 'reaction_on_attack', duration: 'until_next_turn', school: 'Abjuration' },
        usage: { per: 'focus', focus_dc: 11 },
        source: 'shadowdark',
        is_template: true,
        metadata: { spell_type: 'wizard', tier: 1 },
    },
    {
        id: '30000000-0000-4000-a000-050000000005',
        name: 'Detect Magic',
        slug: 'spell_detect_magic',
        description: 'Sense magical auras within Near range for 10 minutes.',
        ability_type: 'spell',
        tier: 1,
        class_restriction: ['Wizard', 'Priest'],
        ancestry_restriction: [],
        level_requirement: 1,
        primary_stat: null,
        mechanics: { range: 'Near', duration: '10_minutes', effect: 'detect_magic', school: 'Divination' },
        usage: { per: 'focus', focus_dc: 10 },
        source: 'shadowdark',
        is_template: true,
        metadata: { spell_type: 'both', tier: 1 },
    },
    {
        id: '30000000-0000-4000-a000-050000000006',
        name: 'Charm Person',
        slug: 'spell_charm_person',
        description: 'A humanoid within Near must WIS save or regard you as a friend for 1 hour.',
        ability_type: 'spell',
        tier: 1,
        class_restriction: ['Wizard'],
        ancestry_restriction: [],
        level_requirement: 1,
        primary_stat: 'INT',
        mechanics: { range: 'Near', save: 'WIS', effect: 'charmed', duration: '1_hour', target: 'humanoid', school: 'Enchantment' },
        usage: { per: 'focus', focus_dc: 11 },
        source: 'shadowdark',
        is_template: true,
        metadata: { spell_type: 'wizard', tier: 1 },
    },
    {
        id: '30000000-0000-4000-a000-050000000007',
        name: 'Feather Fall',
        slug: 'spell_feather_fall',
        description: 'Reaction: Up to 5 creatures within Near fall gently, taking no fall damage.',
        ability_type: 'spell',
        tier: 1,
        class_restriction: ['Wizard'],
        ancestry_restriction: [],
        level_requirement: 1,
        primary_stat: 'INT',
        mechanics: { range: 'Near', trigger: 'reaction_on_fall', targets: 5, effect: 'no_fall_damage', school: 'Transmutation' },
        usage: { per: 'focus', focus_dc: 10 },
        source: 'shadowdark',
        is_template: true,
        metadata: { spell_type: 'wizard', tier: 1 },
    },
    {
        id: '30000000-0000-4000-a000-050000000008',
        name: 'Floating Disk',
        slug: 'spell_floating_disk',
        description: 'A floating disk appears that carries up to 20 gear slots of items.',
        ability_type: 'spell',
        tier: 1,
        class_restriction: ['Wizard'],
        ancestry_restriction: [],
        level_requirement: 1,
        primary_stat: 'INT',
        mechanics: { range: 'Near', capacity_slots: 20, duration: 'focus', school: 'Conjuration' },
        usage: { per: 'focus', focus_dc: 10 },
        source: 'shadowdark',
        is_template: true,
        metadata: { spell_type: 'wizard', tier: 1 },
    },

    // ── Wizard Tier 2 ───────────────────────────────────────────────
    {
        id: '30000000-0000-4000-a000-050000000010',
        name: 'Fireball',
        slug: 'spell_fireball',
        description: 'A ball of fire explodes on a point within Far range. All creatures in Near radius take 4d6 fire damage (DEX save for half).',
        ability_type: 'spell',
        tier: 2,
        class_restriction: ['Wizard'],
        ancestry_restriction: [],
        level_requirement: 3,
        primary_stat: 'INT',
        mechanics: { range: 'Far', damage: '4d6', damage_type: 'fire', save: 'DEX', shape: 'sphere_near', school: 'Evocation' },
        usage: { per: 'focus', focus_dc: 13 },
        source: 'shadowdark',
        is_template: true,
        metadata: { spell_type: 'wizard', tier: 2 },
    },
    {
        id: '30000000-0000-4000-a000-050000000011',
        name: 'Invisibility',
        slug: 'spell_invisibility',
        description: 'A creature you touch becomes invisible for 10 minutes. Breaks on attack or casting.',
        ability_type: 'spell',
        tier: 2,
        class_restriction: ['Wizard'],
        ancestry_restriction: [],
        level_requirement: 3,
        primary_stat: 'INT',
        mechanics: { range: 'Close', effect: 'invisible', duration: '10_minutes', breaks_on: ['attack', 'cast_spell'], school: 'Illusion' },
        usage: { per: 'focus', focus_dc: 12 },
        source: 'shadowdark',
        is_template: true,
        metadata: { spell_type: 'wizard', tier: 2 },
    },
    {
        id: '30000000-0000-4000-a000-050000000012',
        name: 'Web',
        slug: 'spell_web',
        description: 'Fill a Near-sized area with sticky webs. Creatures must STR save or be restrained.',
        ability_type: 'spell',
        tier: 2,
        class_restriction: ['Wizard'],
        ancestry_restriction: [],
        level_requirement: 3,
        primary_stat: 'INT',
        mechanics: { range: 'Near', save: 'STR', effect: 'restrained', shape: 'area_near', duration: 'focus', school: 'Conjuration' },
        usage: { per: 'focus', focus_dc: 12 },
        source: 'shadowdark',
        is_template: true,
        metadata: { spell_type: 'wizard', tier: 2 },
    },
    {
        id: '30000000-0000-4000-a000-050000000013',
        name: 'Mirror Image',
        slug: 'spell_mirror_image',
        description: 'Create 1d4 illusory duplicates. Each absorbs one attack before vanishing.',
        ability_type: 'spell',
        tier: 2,
        class_restriction: ['Wizard'],
        ancestry_restriction: [],
        level_requirement: 3,
        primary_stat: 'INT',
        mechanics: { duplicates: '1d4', effect: 'absorb_attack', duration: 'focus', school: 'Illusion' },
        usage: { per: 'focus', focus_dc: 12 },
        source: 'shadowdark',
        is_template: true,
        metadata: { spell_type: 'wizard', tier: 2 },
    },

    // ── Wizard Tier 3 ───────────────────────────────────────────────
    {
        id: '30000000-0000-4000-a000-050000000020',
        name: 'Lightning Bolt',
        slug: 'spell_lightning_bolt',
        description: 'A bolt of lightning in a line to Far range. All creatures take 6d6 lightning damage (DEX save for half).',
        ability_type: 'spell',
        tier: 3,
        class_restriction: ['Wizard'],
        ancestry_restriction: [],
        level_requirement: 5,
        primary_stat: 'INT',
        mechanics: { range: 'Far', damage: '6d6', damage_type: 'lightning', save: 'DEX', shape: 'line', school: 'Evocation' },
        usage: { per: 'focus', focus_dc: 15 },
        source: 'shadowdark',
        is_template: true,
        metadata: { spell_type: 'wizard', tier: 3 },
    },
    {
        id: '30000000-0000-4000-a000-050000000021',
        name: 'Dispel Magic',
        slug: 'spell_dispel_magic',
        description: 'End one magical effect within Near range.',
        ability_type: 'spell',
        tier: 3,
        class_restriction: ['Wizard', 'Priest'],
        ancestry_restriction: [],
        level_requirement: 5,
        primary_stat: null,
        mechanics: { range: 'Near', effect: 'dispel', target: 'one_magical_effect', school: 'Abjuration' },
        usage: { per: 'focus', focus_dc: 14 },
        source: 'shadowdark',
        is_template: true,
        metadata: { spell_type: 'both', tier: 3 },
    },
];

// ═══════════════════════════════════════════════════════════════════
// GENERAL SKILLS — available to all, resolved by stat checks
// ═══════════════════════════════════════════════════════════════════

const SKILLS: AbilitySeed[] = [
    {
        id: '30000000-0000-4000-a000-060000000001',
        name: 'Athletics',
        slug: 'skill_athletics',
        description: 'Climbing, jumping, swimming, feats of physical prowess.',
        ability_type: 'skill',
        tier: 1,
        class_restriction: [],
        ancestry_restriction: [],
        level_requirement: 1,
        primary_stat: 'STR',
        mechanics: { check_type: 'STR', dc_default: 12, advantage_if: 'background_match' },
        usage: { per: 'always' },
        source: 'shadowdark',
        is_template: true,
        metadata: { backgrounds: ['Soldier', 'Laborer', 'Sailor'] },
    },
    {
        id: '30000000-0000-4000-a000-060000000002',
        name: 'Stealth',
        slug: 'skill_stealth',
        description: 'Sneaking, hiding, moving silently.',
        ability_type: 'skill',
        tier: 1,
        class_restriction: [],
        ancestry_restriction: [],
        level_requirement: 1,
        primary_stat: 'DEX',
        mechanics: { check_type: 'DEX', dc_default: 12, advantage_if: 'background_match', thief_advantage: true },
        usage: { per: 'always' },
        source: 'shadowdark',
        is_template: true,
        metadata: { backgrounds: ['Urchin', 'Ranger', 'Spy'] },
    },
    {
        id: '30000000-0000-4000-a000-060000000003',
        name: 'Perception',
        slug: 'skill_perception',
        description: 'Noticing hidden things, detecting traps, spotting ambushes.',
        ability_type: 'skill',
        tier: 1,
        class_restriction: [],
        ancestry_restriction: [],
        level_requirement: 1,
        primary_stat: 'WIS',
        mechanics: { check_type: 'WIS', dc_default: 12, advantage_if: 'background_match' },
        usage: { per: 'always' },
        source: 'shadowdark',
        is_template: true,
        metadata: { backgrounds: ['Ranger', 'Guard', 'Hunter'] },
    },
    {
        id: '30000000-0000-4000-a000-060000000004',
        name: 'Persuasion',
        slug: 'skill_persuasion',
        description: 'Convincing, negotiating, inspiring, deceiving.',
        ability_type: 'skill',
        tier: 1,
        class_restriction: [],
        ancestry_restriction: [],
        level_requirement: 1,
        primary_stat: 'CHA',
        mechanics: { check_type: 'CHA', dc_default: 12, advantage_if: 'background_match' },
        usage: { per: 'always' },
        source: 'shadowdark',
        is_template: true,
        metadata: { backgrounds: ['Noble', 'Merchant', 'Diplomat'] },
    },
    {
        id: '30000000-0000-4000-a000-060000000005',
        name: 'Arcana',
        slug: 'skill_arcana',
        description: 'Knowledge of magic, identifying spells, understanding arcane phenomena.',
        ability_type: 'skill',
        tier: 1,
        class_restriction: [],
        ancestry_restriction: [],
        level_requirement: 1,
        primary_stat: 'INT',
        mechanics: { check_type: 'INT', dc_default: 12, advantage_if: 'background_match' },
        usage: { per: 'always' },
        source: 'shadowdark',
        is_template: true,
        metadata: { backgrounds: ['Scholar', 'Wizard Apprentice', 'Sage'] },
    },
    {
        id: '30000000-0000-4000-a000-060000000006',
        name: 'Medicine',
        slug: 'skill_medicine',
        description: 'Stabilizing the dying, treating wounds, diagnosing ailments.',
        ability_type: 'skill',
        tier: 1,
        class_restriction: [],
        ancestry_restriction: [],
        level_requirement: 1,
        primary_stat: 'WIS',
        mechanics: { check_type: 'WIS', dc_default: 15, advantage_if: 'background_match' },
        usage: { per: 'always' },
        source: 'shadowdark',
        is_template: true,
        metadata: { backgrounds: ['Herbalist', 'Priest Acolyte', 'Physician'] },
    },
    {
        id: '30000000-0000-4000-a000-060000000007',
        name: 'Survival',
        slug: 'skill_survival',
        description: 'Tracking, foraging, navigating wilderness, weather prediction.',
        ability_type: 'skill',
        tier: 1,
        class_restriction: [],
        ancestry_restriction: [],
        level_requirement: 1,
        primary_stat: 'WIS',
        mechanics: { check_type: 'WIS', dc_default: 12, advantage_if: 'background_match' },
        usage: { per: 'always' },
        source: 'shadowdark',
        is_template: true,
        metadata: { backgrounds: ['Ranger', 'Hunter', 'Farmer'] },
    },
    {
        id: '30000000-0000-4000-a000-060000000008',
        name: 'Intimidation',
        slug: 'skill_intimidation',
        description: 'Threatening, coercing, frightening opponents into submission.',
        ability_type: 'skill',
        tier: 1,
        class_restriction: [],
        ancestry_restriction: [],
        level_requirement: 1,
        primary_stat: 'CHA',
        mechanics: { check_type: 'CHA', dc_default: 12, advantage_if: 'background_match' },
        usage: { per: 'always' },
        source: 'shadowdark',
        is_template: true,
        metadata: { backgrounds: ['Soldier', 'Criminal', 'Gladiator'] },
    },
];

// ═══════════════════════════════════════════════════════════════════
// EXPORTS
// ═══════════════════════════════════════════════════════════════════

export const ALL_SEED_ABILITIES: AbilitySeed[] = [
    ...ANCESTRY_FEATURES,
    ...CLASS_FEATURES,
    ...TALENTS,
    ...SPELLS,
    ...SKILLS,
];
