/**
 * Shadowdark Item Seeds — Base items from the Shadowdark RPG rules.
 * All items are templates (is_template: true). Player instances are created from these.
 */

// ── Deterministic UUIDs for seed items ──────────────────────────────
// Gear: 20000000-0000-4000-a000-0000000000XX
// Weapons: 20000000-0000-4000-a000-0000000001XX
// Armor: 20000000-0000-4000-a000-0000000002XX
// Scrolls/Magic: 20000000-0000-4000-a000-0000000003XX

interface ItemSeed {
    id: string;
    name: string;
    base_type: string;
    category: string;
    subcategory?: string;
    rarity: string;
    cost_gp: number;
    slots: number;
    stats: Record<string, any>;
    bonuses: Record<string, any>;
    perks: any[];
    class_restrictions: string[];
    is_template: boolean;
    metadata?: Record<string, any>;
}

// ═══════════════════════════════════════════════════════════════════
// BASIC GEAR
// ═══════════════════════════════════════════════════════════════════

const GEAR: ItemSeed[] = [
    {
        id: '20000000-0000-4000-a000-000000000001',
        name: 'Torch',
        base_type: 'Torch',
        category: 'Gear',
        subcategory: 'LightSource',
        rarity: 'Common',
        cost_gp: 0,
        slots: 1,
        stats: { duration_seconds: 3600, light_range: 'Near', description: 'Burns for 1 hour real time. Illuminates Near distance.' },
        bonuses: {},
        perks: [],
        class_restrictions: [],
        is_template: true,
    },
    {
        id: '20000000-0000-4000-a000-000000000002',
        name: 'Lantern',
        base_type: 'Lantern',
        category: 'Gear',
        subcategory: 'LightSource',
        rarity: 'Common',
        cost_gp: 10,
        slots: 1,
        stats: { duration_seconds: 3600, light_range: 'DoubleNear', description: 'Requires oil flask. Illuminates double Near distance.' },
        bonuses: {},
        perks: [],
        class_restrictions: [],
        is_template: true,
    },
    {
        id: '20000000-0000-4000-a000-000000000003',
        name: 'Oil Flask',
        base_type: 'Oil Flask',
        category: 'Gear',
        subcategory: 'Consumable',
        rarity: 'Common',
        cost_gp: 0,
        slots: 1,
        stats: { uses: 1, description: 'Fuel for lantern or throw as weapon (Near range, 1d6 fire damage on hit).' },
        bonuses: {},
        perks: [],
        class_restrictions: [],
        is_template: true,
    },
    {
        id: '20000000-0000-4000-a000-000000000004',
        name: 'Rations',
        base_type: 'Rations',
        category: 'Gear',
        subcategory: 'Consumable',
        rarity: 'Common',
        cost_gp: 0,
        slots: 1,
        stats: { uses: 3, description: 'Food for 3 days. One slot holds 3 days of rations.' },
        bonuses: {},
        perks: [],
        class_restrictions: [],
        is_template: true,
    },
    {
        id: '20000000-0000-4000-a000-000000000005',
        name: 'Rope (60 ft)',
        base_type: 'Rope',
        category: 'Gear',
        subcategory: 'Tool',
        rarity: 'Common',
        cost_gp: 1,
        slots: 1,
        stats: { description: '60 feet of hempen rope. Essential for climbing and restraining.' },
        bonuses: {},
        perks: [],
        class_restrictions: [],
        is_template: true,
    },
    {
        id: '20000000-0000-4000-a000-000000000006',
        name: 'Grappling Hook',
        base_type: 'Grappling Hook',
        category: 'Gear',
        subcategory: 'Tool',
        rarity: 'Common',
        cost_gp: 1,
        slots: 1,
        stats: { description: 'Attach to rope for climbing. Throw to Near range.' },
        bonuses: {},
        perks: [],
        class_restrictions: [],
        is_template: true,
    },
    {
        id: '20000000-0000-4000-a000-000000000007',
        name: 'Crowbar',
        base_type: 'Crowbar',
        category: 'Gear',
        subcategory: 'Tool',
        rarity: 'Common',
        cost_gp: 1,
        slots: 1,
        stats: { description: 'Advantage on STR checks to force open doors, chests, and lids.' },
        bonuses: {},
        perks: [],
        class_restrictions: [],
        is_template: true,
    },
    {
        id: '20000000-0000-4000-a000-000000000008',
        name: 'Iron Spikes (10)',
        base_type: 'Iron Spikes',
        category: 'Gear',
        subcategory: 'Tool',
        rarity: 'Common',
        cost_gp: 1,
        slots: 1,
        stats: { uses: 10, description: 'Hammer into walls, jam doors, or use as pitons for climbing.' },
        bonuses: {},
        perks: [],
        class_restrictions: [],
        is_template: true,
    },
    {
        id: '20000000-0000-4000-a000-000000000009',
        name: 'Caltrops (one bag)',
        base_type: 'Caltrops',
        category: 'Gear',
        subcategory: 'Tool',
        rarity: 'Common',
        cost_gp: 1,
        slots: 1,
        stats: { description: 'Covers Close area. Creatures entering must DEX check DC 12 or take 1d4 damage and half move speed.' },
        bonuses: {},
        perks: [],
        class_restrictions: [],
        is_template: true,
    },
    {
        id: '20000000-0000-4000-a000-000000000010',
        name: '10-Foot Pole',
        base_type: '10-Foot Pole',
        category: 'Gear',
        subcategory: 'Tool',
        rarity: 'Common',
        cost_gp: 0,
        slots: 1,
        stats: { description: 'Poke suspicious floors, trigger traps safely from a distance.' },
        bonuses: {},
        perks: [],
        class_restrictions: [],
        is_template: true,
    },
    {
        id: '20000000-0000-4000-a000-000000000011',
        name: 'Waterskin',
        base_type: 'Waterskin',
        category: 'Gear',
        subcategory: 'Consumable',
        rarity: 'Common',
        cost_gp: 0,
        slots: 1,
        stats: { uses: 1, description: 'Holds enough water for 1 day.' },
        bonuses: {},
        perks: [],
        class_restrictions: [],
        is_template: true,
    },
    {
        id: '20000000-0000-4000-a000-000000000012',
        name: 'Backpack',
        base_type: 'Backpack',
        category: 'Gear',
        subcategory: 'Container',
        rarity: 'Common',
        cost_gp: 2,
        slots: 0,
        stats: { description: 'Standard adventurer backpack. Does not take a gear slot.' },
        bonuses: {},
        perks: [],
        class_restrictions: [],
        is_template: true,
    },
    {
        id: '20000000-0000-4000-a000-000000000013',
        name: 'Thieves\' Tools',
        base_type: 'Thieves Tools',
        category: 'Gear',
        subcategory: 'Tool',
        rarity: 'Common',
        cost_gp: 25,
        slots: 1,
        stats: { description: 'Required to pick locks and disarm traps. Thief class feature.' },
        bonuses: {},
        perks: [],
        class_restrictions: ['Thief'],
        is_template: true,
    },
    {
        id: '20000000-0000-4000-a000-000000000014',
        name: 'Flint & Steel',
        base_type: 'Flint and Steel',
        category: 'Gear',
        subcategory: 'Tool',
        rarity: 'Common',
        cost_gp: 0,
        slots: 1,
        stats: { description: 'Start fires and light torches. Essential survival gear.' },
        bonuses: {},
        perks: [],
        class_restrictions: [],
        is_template: true,
    },
    {
        id: '20000000-0000-4000-a000-000000000015',
        name: 'Holy Symbol',
        base_type: 'Holy Symbol',
        category: 'Gear',
        subcategory: 'Tool',
        rarity: 'Common',
        cost_gp: 25,
        slots: 1,
        stats: { description: 'Required to cast Priest spells. Can be used to turn undead.' },
        bonuses: {},
        perks: [],
        class_restrictions: ['Priest'],
        is_template: true,
    },
    {
        id: '20000000-0000-4000-a000-000000000016',
        name: 'Spellbook',
        base_type: 'Spellbook',
        category: 'Gear',
        subcategory: 'Tool',
        rarity: 'Common',
        cost_gp: 50,
        slots: 1,
        stats: { description: 'Required to prepare Wizard spells. Contains known spells.' },
        bonuses: {},
        perks: [],
        class_restrictions: ['Wizard'],
        is_template: true,
    },
];

// ═══════════════════════════════════════════════════════════════════
// WEAPONS — Based on Shadowdark weapon tables
// ═══════════════════════════════════════════════════════════════════

const WEAPONS: ItemSeed[] = [
    // ── Melee Weapons ───────────────────────────────────────────────
    {
        id: '20000000-0000-4000-a000-000000000101',
        name: 'Dagger',
        base_type: 'Dagger',
        category: 'Weapon',
        subcategory: 'Melee',
        rarity: 'Common',
        cost_gp: 3,
        slots: 1,
        stats: { damage: '1d4', range: 'Close', properties: ['Finesse', 'Thrown'] },
        bonuses: {},
        perks: [],
        class_restrictions: [],
        is_template: true,
    },
    {
        id: '20000000-0000-4000-a000-000000000102',
        name: 'Club',
        base_type: 'Club',
        category: 'Weapon',
        subcategory: 'Melee',
        rarity: 'Common',
        cost_gp: 0,
        slots: 1,
        stats: { damage: '1d4', range: 'Close', properties: [] },
        bonuses: {},
        perks: [],
        class_restrictions: [],
        is_template: true,
    },
    {
        id: '20000000-0000-4000-a000-000000000103',
        name: 'Staff',
        base_type: 'Staff',
        category: 'Weapon',
        subcategory: 'Melee',
        rarity: 'Common',
        cost_gp: 0,
        slots: 1,
        stats: { damage: '1d4', range: 'Close', properties: ['TwoHanded'] },
        bonuses: {},
        perks: [],
        class_restrictions: [],
        is_template: true,
    },
    {
        id: '20000000-0000-4000-a000-000000000104',
        name: 'Shortsword',
        base_type: 'Shortsword',
        category: 'Weapon',
        subcategory: 'Melee',
        rarity: 'Common',
        cost_gp: 7,
        slots: 1,
        stats: { damage: '1d6', range: 'Close', properties: ['Finesse'] },
        bonuses: {},
        perks: [],
        class_restrictions: [],
        is_template: true,
    },
    {
        id: '20000000-0000-4000-a000-000000000105',
        name: 'Handaxe',
        base_type: 'Handaxe',
        category: 'Weapon',
        subcategory: 'Melee',
        rarity: 'Common',
        cost_gp: 5,
        slots: 1,
        stats: { damage: '1d6', range: 'Close', properties: ['Thrown'] },
        bonuses: {},
        perks: [],
        class_restrictions: [],
        is_template: true,
    },
    {
        id: '20000000-0000-4000-a000-000000000106',
        name: 'Spear',
        base_type: 'Spear',
        category: 'Weapon',
        subcategory: 'Melee',
        rarity: 'Common',
        cost_gp: 1,
        slots: 1,
        stats: { damage: '1d6', range: 'Close', properties: ['Versatile', 'Thrown'], versatile_damage: '1d8' },
        bonuses: {},
        perks: [],
        class_restrictions: [],
        is_template: true,
    },
    {
        id: '20000000-0000-4000-a000-000000000107',
        name: 'Mace',
        base_type: 'Mace',
        category: 'Weapon',
        subcategory: 'Melee',
        rarity: 'Common',
        cost_gp: 5,
        slots: 1,
        stats: { damage: '1d6', range: 'Close', properties: [] },
        bonuses: {},
        perks: [],
        class_restrictions: [],
        is_template: true,
    },
    {
        id: '20000000-0000-4000-a000-000000000108',
        name: 'Warhammer',
        base_type: 'Warhammer',
        category: 'Weapon',
        subcategory: 'Melee',
        rarity: 'Common',
        cost_gp: 15,
        slots: 1,
        stats: { damage: '1d8', range: 'Close', properties: ['Versatile'], versatile_damage: '1d10' },
        bonuses: {},
        perks: [],
        class_restrictions: ['Fighter', 'Priest'],
        is_template: true,
    },
    {
        id: '20000000-0000-4000-a000-000000000109',
        name: 'Longsword',
        base_type: 'Longsword',
        category: 'Weapon',
        subcategory: 'Melee',
        rarity: 'Common',
        cost_gp: 15,
        slots: 1,
        stats: { damage: '1d8', range: 'Close', properties: ['Versatile'], versatile_damage: '1d10' },
        bonuses: {},
        perks: [],
        class_restrictions: ['Fighter'],
        is_template: true,
    },
    {
        id: '20000000-0000-4000-a000-000000000110',
        name: 'Battleaxe',
        base_type: 'Battleaxe',
        category: 'Weapon',
        subcategory: 'Melee',
        rarity: 'Common',
        cost_gp: 10,
        slots: 1,
        stats: { damage: '1d8', range: 'Close', properties: ['Versatile'], versatile_damage: '1d10' },
        bonuses: {},
        perks: [],
        class_restrictions: ['Fighter'],
        is_template: true,
    },
    {
        id: '20000000-0000-4000-a000-000000000111',
        name: 'Greatsword',
        base_type: 'Greatsword',
        category: 'Weapon',
        subcategory: 'Melee',
        rarity: 'Common',
        cost_gp: 50,
        slots: 2,
        stats: { damage: '1d12', range: 'Close', properties: ['TwoHanded'] },
        bonuses: {},
        perks: [],
        class_restrictions: ['Fighter'],
        is_template: true,
    },
    {
        id: '20000000-0000-4000-a000-000000000112',
        name: 'Greataxe',
        base_type: 'Greataxe',
        category: 'Weapon',
        subcategory: 'Melee',
        rarity: 'Common',
        cost_gp: 30,
        slots: 2,
        stats: { damage: '1d10', range: 'Close', properties: ['TwoHanded'] },
        bonuses: {},
        perks: [],
        class_restrictions: ['Fighter'],
        is_template: true,
    },

    // ── Ranged Weapons ──────────────────────────────────────────────
    {
        id: '20000000-0000-4000-a000-000000000120',
        name: 'Shortbow',
        base_type: 'Shortbow',
        category: 'Weapon',
        subcategory: 'Ranged',
        rarity: 'Common',
        cost_gp: 25,
        slots: 1,
        stats: { damage: '1d4', range: 'Far', properties: ['TwoHanded'] },
        bonuses: {},
        perks: [],
        class_restrictions: [],
        is_template: true,
    },
    {
        id: '20000000-0000-4000-a000-000000000121',
        name: 'Longbow',
        base_type: 'Longbow',
        category: 'Weapon',
        subcategory: 'Ranged',
        rarity: 'Common',
        cost_gp: 50,
        slots: 1,
        stats: { damage: '1d8', range: 'Far', properties: ['TwoHanded'] },
        bonuses: {},
        perks: [],
        class_restrictions: ['Fighter'],
        is_template: true,
    },
    {
        id: '20000000-0000-4000-a000-000000000122',
        name: 'Crossbow',
        base_type: 'Crossbow',
        category: 'Weapon',
        subcategory: 'Ranged',
        rarity: 'Common',
        cost_gp: 25,
        slots: 1,
        stats: { damage: '1d6', range: 'Far', properties: ['TwoHanded', 'Loading'] },
        bonuses: {},
        perks: [],
        class_restrictions: [],
        is_template: true,
    },
    {
        id: '20000000-0000-4000-a000-000000000123',
        name: 'Sling',
        base_type: 'Sling',
        category: 'Weapon',
        subcategory: 'Ranged',
        rarity: 'Common',
        cost_gp: 0,
        slots: 1,
        stats: { damage: '1d4', range: 'Near', properties: [] },
        bonuses: {},
        perks: [],
        class_restrictions: [],
        is_template: true,
    },
    {
        id: '20000000-0000-4000-a000-000000000124',
        name: 'Arrows (20)',
        base_type: 'Arrows',
        category: 'Gear',
        subcategory: 'Consumable',
        rarity: 'Common',
        cost_gp: 1,
        slots: 1,
        stats: { uses: 20, description: 'Ammunition for shortbow and longbow.' },
        bonuses: {},
        perks: [],
        class_restrictions: [],
        is_template: true,
    },
    {
        id: '20000000-0000-4000-a000-000000000125',
        name: 'Crossbow Bolts (20)',
        base_type: 'Bolts',
        category: 'Gear',
        subcategory: 'Consumable',
        rarity: 'Common',
        cost_gp: 1,
        slots: 1,
        stats: { uses: 20, description: 'Ammunition for crossbow.' },
        bonuses: {},
        perks: [],
        class_restrictions: [],
        is_template: true,
    },
];

// ═══════════════════════════════════════════════════════════════════
// ARMOR — Based on Shadowdark armor tables
// ═══════════════════════════════════════════════════════════════════

const ARMOR: ItemSeed[] = [
    {
        id: '20000000-0000-4000-a000-000000000201',
        name: 'Leather Armor',
        base_type: 'Leather Armor',
        category: 'Armor',
        subcategory: 'Light',
        rarity: 'Common',
        cost_gp: 10,
        slots: 1,
        stats: { ac_base: 11, ac_dex: true, penalties: [] },
        bonuses: {},
        perks: [],
        class_restrictions: [],
        is_template: true,
    },
    {
        id: '20000000-0000-4000-a000-000000000202',
        name: 'Chainmail',
        base_type: 'Chainmail',
        category: 'Armor',
        subcategory: 'Medium',
        rarity: 'Common',
        cost_gp: 75,
        slots: 2,
        stats: { ac_base: 13, ac_dex: true, penalties: ['stealth', 'swimming'] },
        bonuses: {},
        perks: [],
        class_restrictions: ['Fighter', 'Priest'],
        is_template: true,
    },
    {
        id: '20000000-0000-4000-a000-000000000203',
        name: 'Plate Armor',
        base_type: 'Plate Armor',
        category: 'Armor',
        subcategory: 'Heavy',
        rarity: 'Common',
        cost_gp: 1500,
        slots: 3,
        stats: { ac_base: 15, ac_dex: false, penalties: ['stealth', 'swimming_impossible'] },
        bonuses: {},
        perks: [],
        class_restrictions: ['Fighter'],
        is_template: true,
    },
    {
        id: '20000000-0000-4000-a000-000000000204',
        name: 'Shield',
        base_type: 'Shield',
        category: 'Armor',
        subcategory: 'Shield',
        rarity: 'Common',
        cost_gp: 10,
        slots: 1,
        stats: { ac_base: 0, ac_dex: false, penalties: [], description: '+2 to AC. Occupies one hand.' },
        bonuses: { ac_bonus: 2 },
        perks: [],
        class_restrictions: ['Fighter', 'Priest'],
        is_template: true,
    },
    {
        id: '20000000-0000-4000-a000-000000000205',
        name: 'Mithril Chainmail',
        base_type: 'Mithril Chainmail',
        category: 'Armor',
        subcategory: 'Medium',
        rarity: 'Rare',
        cost_gp: 500,
        slots: 1,
        stats: { ac_base: 13, ac_dex: true, penalties: [] },
        bonuses: {},
        perks: ['Lightweight: no stealth or swimming penalties'],
        class_restrictions: ['Fighter', 'Priest'],
        is_template: true,
        metadata: { material: 'mithril' },
    },
    {
        id: '20000000-0000-4000-a000-000000000206',
        name: 'Mithril Plate Armor',
        base_type: 'Mithril Plate',
        category: 'Armor',
        subcategory: 'Heavy',
        rarity: 'Rare',
        cost_gp: 5000,
        slots: 2,
        stats: { ac_base: 15, ac_dex: false, penalties: [] },
        bonuses: {},
        perks: ['Lightweight: no stealth or swimming penalties'],
        class_restrictions: ['Fighter'],
        is_template: true,
        metadata: { material: 'mithril' },
    },
];

// ═══════════════════════════════════════════════════════════════════
// SCROLLS & MAGIC — Priest and Wizard spells as consumables
// ═══════════════════════════════════════════════════════════════════

const MAGIC: ItemSeed[] = [
    // ── Priest Scrolls (Tier 1) ─────────────────────────────────────
    {
        id: '20000000-0000-4000-a000-000000000301',
        name: 'Scroll of Cure Wounds',
        base_type: 'Scroll',
        category: 'Scroll',
        subcategory: undefined,
        rarity: 'Common',
        cost_gp: 50,
        slots: 1,
        stats: { spell: 'Cure Wounds', charges: 1, break_on_nat1: false, description: 'Restore 1d8 HP to a creature you touch.' },
        bonuses: {},
        perks: [],
        class_restrictions: ['Priest'],
        is_template: true,
    },
    {
        id: '20000000-0000-4000-a000-000000000302',
        name: 'Scroll of Protection from Evil',
        base_type: 'Scroll',
        category: 'Scroll',
        rarity: 'Common',
        cost_gp: 50,
        slots: 1,
        stats: { spell: 'Protection from Evil', charges: 1, break_on_nat1: false, description: 'Ward against undead and fiends. +1 AC, advantage on saves vs evil creatures.' },
        bonuses: {},
        perks: [],
        class_restrictions: ['Priest'],
        is_template: true,
    },
    {
        id: '20000000-0000-4000-a000-000000000303',
        name: 'Scroll of Light',
        base_type: 'Scroll',
        category: 'Scroll',
        rarity: 'Common',
        cost_gp: 25,
        slots: 1,
        stats: { spell: 'Light', charges: 1, break_on_nat1: false, description: 'Object shines like a torch for 1 hour real time.' },
        bonuses: {},
        perks: [],
        class_restrictions: ['Priest', 'Wizard'],
        is_template: true,
    },
    {
        id: '20000000-0000-4000-a000-000000000304',
        name: 'Scroll of Turn Undead',
        base_type: 'Scroll',
        category: 'Scroll',
        rarity: 'Common',
        cost_gp: 75,
        slots: 1,
        stats: { spell: 'Turn Undead', charges: 1, break_on_nat1: false, description: 'All undead within Near must make CHA save or flee for 1d4 rounds.' },
        bonuses: {},
        perks: [],
        class_restrictions: ['Priest'],
        is_template: true,
    },

    // ── Wizard Scrolls (Tier 1) ─────────────────────────────────────
    {
        id: '20000000-0000-4000-a000-000000000310',
        name: 'Scroll of Magic Missile',
        base_type: 'Scroll',
        category: 'Scroll',
        rarity: 'Common',
        cost_gp: 50,
        slots: 1,
        stats: { spell: 'Magic Missile', charges: 1, break_on_nat1: false, description: 'Launch 3 magic darts that auto-hit. Each deals 1d4+1 force damage.' },
        bonuses: {},
        perks: [],
        class_restrictions: ['Wizard'],
        is_template: true,
    },
    {
        id: '20000000-0000-4000-a000-000000000311',
        name: 'Scroll of Sleep',
        base_type: 'Scroll',
        category: 'Scroll',
        rarity: 'Common',
        cost_gp: 50,
        slots: 1,
        stats: { spell: 'Sleep', charges: 1, break_on_nat1: false, description: 'Put 4d6 HP of creatures to sleep within Near range.' },
        bonuses: {},
        perks: [],
        class_restrictions: ['Wizard'],
        is_template: true,
    },
    {
        id: '20000000-0000-4000-a000-000000000312',
        name: 'Scroll of Burning Hands',
        base_type: 'Scroll',
        category: 'Scroll',
        rarity: 'Common',
        cost_gp: 50,
        slots: 1,
        stats: { spell: 'Burning Hands', charges: 1, break_on_nat1: false, description: 'Cone of fire. All creatures in Close range take 2d6 fire damage (DEX save for half).' },
        bonuses: {},
        perks: [],
        class_restrictions: ['Wizard'],
        is_template: true,
    },
    {
        id: '20000000-0000-4000-a000-000000000313',
        name: 'Scroll of Shield',
        base_type: 'Scroll',
        category: 'Scroll',
        rarity: 'Common',
        cost_gp: 50,
        slots: 1,
        stats: { spell: 'Shield', charges: 1, break_on_nat1: false, description: 'Reaction: +5 AC until your next turn.' },
        bonuses: {},
        perks: [],
        class_restrictions: ['Wizard'],
        is_template: true,
    },
    {
        id: '20000000-0000-4000-a000-000000000314',
        name: 'Scroll of Detect Magic',
        base_type: 'Scroll',
        category: 'Scroll',
        rarity: 'Common',
        cost_gp: 25,
        slots: 1,
        stats: { spell: 'Detect Magic', charges: 1, break_on_nat1: false, description: 'Sense magical auras within Near range for 10 minutes.' },
        bonuses: {},
        perks: [],
        class_restrictions: ['Wizard', 'Priest'],
        is_template: true,
    },

    // ── Wands ───────────────────────────────────────────────────────
    {
        id: '20000000-0000-4000-a000-000000000320',
        name: 'Wand of Magic Missiles',
        base_type: 'Wand',
        category: 'Wand',
        rarity: 'Uncommon',
        cost_gp: 200,
        slots: 1,
        stats: { spell: 'Magic Missile', charges: 5, break_on_nat1: true, description: 'Cast Magic Missile. On natural 1 on d20 casting check, the wand shatters.' },
        bonuses: {},
        perks: [],
        class_restrictions: ['Wizard'],
        is_template: true,
    },
    {
        id: '20000000-0000-4000-a000-000000000321',
        name: 'Wand of Healing',
        base_type: 'Wand',
        category: 'Wand',
        rarity: 'Uncommon',
        cost_gp: 200,
        slots: 1,
        stats: { spell: 'Cure Wounds', charges: 5, break_on_nat1: true, description: 'Cast Cure Wounds. Risk of shattering on natural 1.' },
        bonuses: {},
        perks: [],
        class_restrictions: ['Priest'],
        is_template: true,
    },

    // ── Potions ─────────────────────────────────────────────────────
    {
        id: '20000000-0000-4000-a000-000000000330',
        name: 'Potion of Healing',
        base_type: 'Potion',
        category: 'Magic',
        subcategory: undefined,
        rarity: 'Common',
        cost_gp: 50,
        slots: 1,
        stats: { uses: 1, description: 'Drink to restore 2d4+2 HP.' },
        bonuses: {},
        perks: [],
        class_restrictions: [],
        is_template: true,
    },
    {
        id: '20000000-0000-4000-a000-000000000331',
        name: 'Potion of Invisibility',
        base_type: 'Potion',
        category: 'Magic',
        rarity: 'Rare',
        cost_gp: 300,
        slots: 1,
        stats: { uses: 1, description: 'Become invisible for 10 minutes. Breaks when you attack or cast a spell.' },
        bonuses: {},
        perks: [],
        class_restrictions: [],
        is_template: true,
    },
    {
        id: '20000000-0000-4000-a000-000000000332',
        name: 'Potion of Giant Strength',
        base_type: 'Potion',
        category: 'Magic',
        rarity: 'Rare',
        cost_gp: 500,
        slots: 1,
        stats: { uses: 1, description: 'STR becomes 18 for 10 minutes. +4 to melee attack/damage.' },
        bonuses: {},
        perks: [],
        class_restrictions: [],
        is_template: true,
    },
];

// ═══════════════════════════════════════════════════════════════════
// CLASS STARTER KITS — default items given to each class
// ═══════════════════════════════════════════════════════════════════

export const CLASS_STARTER_ITEMS: Record<string, string[]> = {
    Fighter: [
        '20000000-0000-4000-a000-000000000109', // Longsword
        '20000000-0000-4000-a000-000000000204', // Shield
        '20000000-0000-4000-a000-000000000201', // Leather Armor
        '20000000-0000-4000-a000-000000000001', // Torch x2
        '20000000-0000-4000-a000-000000000004', // Rations
        '20000000-0000-4000-a000-000000000005', // Rope
    ],
    Priest: [
        '20000000-0000-4000-a000-000000000107', // Mace
        '20000000-0000-4000-a000-000000000204', // Shield
        '20000000-0000-4000-a000-000000000201', // Leather Armor
        '20000000-0000-4000-a000-000000000015', // Holy Symbol
        '20000000-0000-4000-a000-000000000001', // Torch
        '20000000-0000-4000-a000-000000000004', // Rations
    ],
    Thief: [
        '20000000-0000-4000-a000-000000000104', // Shortsword
        '20000000-0000-4000-a000-000000000101', // Dagger
        '20000000-0000-4000-a000-000000000201', // Leather Armor
        '20000000-0000-4000-a000-000000000013', // Thieves' Tools
        '20000000-0000-4000-a000-000000000005', // Rope
        '20000000-0000-4000-a000-000000000001', // Torch
    ],
    Wizard: [
        '20000000-0000-4000-a000-000000000103', // Staff
        '20000000-0000-4000-a000-000000000101', // Dagger
        '20000000-0000-4000-a000-000000000016', // Spellbook
        '20000000-0000-4000-a000-000000000310', // Scroll of Magic Missile
        '20000000-0000-4000-a000-000000000001', // Torch
        '20000000-0000-4000-a000-000000000004', // Rations
    ],
};

export const ALL_SEED_ITEMS: ItemSeed[] = [
    ...GEAR,
    ...WEAPONS,
    ...ARMOR,
    ...MAGIC,
];
