export enum ItemCategory {
    Weapon = 'Weapon',
    Artifact = 'Artifact', // Armor, Helmets
    Talisman = 'Talisman', // Trinkets, max 2 slots
    Material = 'Material', // Copper, Leather, Runes
    QuestItem = 'QuestItem'// Keys, Lore scrolls
}

export enum ItemRarity {
    Common = 'Common',     // 60%
    Uncommon = 'Uncommon', // 25%
    Rare = 'Rare',         // 10%
    Epic = 'Epic',         // 4%
    Legendary = 'Legendary'// 1%
}

export interface ItemAttributes {
    baseStat: number;
    rarityMultiplier: number;
    perks: string[]; // Custom magic effects generated by AI
}

export interface BaseItem {
    id: string; // Internal UUID
    name: string;
    category: ItemCategory;
    rarity: ItemRarity;
    isNft: boolean;
    attributes: ItemAttributes;
    aiHistory?: string; // Generated lore text mapped to Soroban Minting
}

export interface Weapon extends BaseItem {
    category: ItemCategory.Weapon;
    weaponSubtype: 'Sword' | 'Bow' | 'Staff' | 'Dagger';
}
