-- Migration for NFT-DND Quest System
-- Description: Creates tables for locations, items, quests, and quest history

-- 1. Locations
CREATE TABLE IF NOT EXISTS public.locations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    biome_type TEXT NOT NULL,
    room_type TEXT NOT NULL,
    threat_level INT DEFAULT 1,
    coordinates JSONB DEFAULT '{"x": 0, "y": 0, "z": 0}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for locations
ALTER TABLE public.locations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for service role" ON public.locations FOR SELECT USING (true);
CREATE POLICY "Enable all for service role" ON public.locations FOR ALL USING (true) WITH CHECK (true);

-- 2. Items
CREATE TABLE IF NOT EXISTS public.items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    rarity TEXT NOT NULL,
    is_nft BOOLEAN DEFAULT false,
    attributes JSONB DEFAULT '{}'::jsonb,
    ai_history TEXT, -- Legend generated by AI
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for items
ALTER TABLE public.items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for service role" ON public.items FOR SELECT USING (true);
CREATE POLICY "Enable all for service role" ON public.items FOR ALL USING (true) WITH CHECK (true);

-- 3. Quests
CREATE TABLE IF NOT EXISTS public.quests (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    party_members JSONB DEFAULT '[]'::jsonb, -- Array of character UUIDs
    status TEXT NOT NULL DEFAULT 'InProgress', -- InProgress, Success, PartyWiped
    start_time TIMESTAMPTZ DEFAULT NOW(),
    end_time TIMESTAMPTZ,
    loot_dropped BOOLEAN DEFAULT false,
    stat_changes JSONB DEFAULT '{}'::jsonb, -- e.g. {"char_id": {"hp": -5, "xp": +100}}
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for quests
ALTER TABLE public.quests ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for service role" ON public.quests FOR SELECT USING (true);
CREATE POLICY "Enable all for service role" ON public.quests FOR ALL USING (true) WITH CHECK (true);

-- 4. Quest History (The Chronicle)
CREATE TABLE IF NOT EXISTS public.quest_history (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    quest_id UUID NOT NULL REFERENCES public.quests(id) ON DELETE CASCADE,
    location_id UUID REFERENCES public.locations(id) ON DELETE SET NULL,
    player_action TEXT,
    player_background TEXT,
    player_roll INT,
    dm_roll INT,
    ai_narrative TEXT,
    engine_trigger TEXT,
    on_chain_event BOOLEAN DEFAULT false,
    movement_vector JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for quest_history
ALTER TABLE public.quest_history ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for service role" ON public.quest_history FOR SELECT USING (true);
CREATE POLICY "Enable all for service role" ON public.quest_history FOR ALL USING (true) WITH CHECK (true);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_quests_status ON public.quests(status);
CREATE INDEX IF NOT EXISTS idx_quest_history_quest_id ON public.quest_history(quest_id);
CREATE INDEX IF NOT EXISTS idx_quest_history_created_at ON public.quest_history(created_at);
