#![no_main]

use risc0_zkvm::guest::env;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

risc0_zkvm::guest::entry!(main);

#[derive(Serialize, Deserialize, Debug)]
pub struct DiceRollInput {
    pub seed: String,
    pub bound: u32,
}

#[derive(Serialize, Deserialize, Debug)]
pub struct DiceRollOutput {
    pub seed: String,
    pub bound: u32,
    pub result: u32,
}

fn main() {
    // Read the input securely correctly from the host
    let input: DiceRollInput = env::read();

    // Deterministically generate the roll based on the seed
    let mut hasher = Sha256::new();
    hasher.update(input.seed.as_bytes());
    let hash_result = hasher.finalize();

    // Convert the first 4 bytes of the hash into an integer
    // We use exactly the same deterministic logic that would be verifiable
    let hash_int = u32::from_be_bytes([
        hash_result[0],
        hash_result[1],
        hash_result[2],
        hash_result[3],
    ]);

    // Modulo math for the dice roll (1 to bound)
    let roll_result = (hash_int % input.bound) + 1;

    let output = DiceRollOutput {
        seed: input.seed,
        bound: input.bound,
        result: roll_result,
    };

    // Commit the output to the journal. The verifier will automatically verify
    // that this output was generated by this exact code given the inputs.
    env::commit(&output);
}
