use clap::Parser;
use risc0_zkvm::{default_prover, ExecutorEnv};
use serde::{Deserialize, Serialize};

// The methods crate is generated by risc0-build.
// The guest ELF file and the generated image ID will be available as constants.
use methods::{GUEST_ELF, GUEST_ID};

#[derive(Serialize, Deserialize, Debug)]
pub struct DiceRollInput {
    pub seed: String,
    pub bound: u32,
}

#[derive(Serialize, Deserialize, Debug)]
pub struct DiceRollOutput {
    pub seed: String,
    pub bound: u32,
    pub result: u32,
}

#[derive(Serialize)]
pub struct ProofResult {
    pub receipt_base64: String,
    pub result: DiceRollOutput,
    pub image_id: String,
}

#[derive(Parser, Debug)]
#[command(author, version, about, long_about = None)]
struct Args {
    #[arg(short, long)]
    seed: String,

    #[arg(short, long)]
    bound: u32,
}

fn main() {
    let args = Args::parse();

    let input = DiceRollInput {
        seed: args.seed,
        bound: args.bound,
    };

    // Build the executor environment, providing the input
    let env = ExecutorEnv::builder()
        .write(&input)
        .unwrap()
        .build()
        .unwrap();

    // Setup the default prover
    let prover = default_prover();

    // Generate the receipt by proving the execution of the guest program
    let receipt = prover.prove(env, GUEST_ELF).unwrap().receipt;

    // Decode the journal (the output committed by the guest)
    let output: DiceRollOutput = receipt.journal.decode().unwrap();

    // Verify the receipt locally to ensure it's valid before sending to client
    receipt.verify(GUEST_ID).unwrap();

    // Serialize the receipt using bincode
    let receipt_bytes = bincode::serialize(&receipt).unwrap();
    let receipt_base64 = base64::encode(receipt_bytes);
    
    // Format the Image ID as hex to use in the smart contract later
    let image_id_hex = hex::encode(bytemuck::cast::<[u32; 8], [u8; 32]>(GUEST_ID));

    let final_output = ProofResult {
        receipt_base64,
        result: output,
        image_id: image_id_hex,
    };

    // Print the JSON output strictly to stdout
    println!("{}", serde_json::to_string(&final_output).unwrap());
}
